
server:
  port: 8700

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    table: flyway_user_history
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_stage_db
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: true
        format_sql: true

logging:
  file:
    name: src/main/resources/script/stage_log.log
    clean-history-on-start: true
  level:
    root: INFO 
    org:
      flywaydb: DEBUG
      hibernate:
        SQL: DEBUG 
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG
