CREATE TABLE address (
  address_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  full_address VARCHAR(255),
  postal_code VARCHAR(255),
  city VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);
