name: Build and Push Docker Image to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io 

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.ACR_NAME }}.azurecr.io/user-service:dev

    - name: Log in to Azure
      if: github.event_name == 'push'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.CREDS }}
        auth-type: SERVICE_PRINCIPAL

    - name: Force new revision of Azure Container App
      if: github.event_name == 'push'
      run: |
        az containerapp update \
          --name ${{ secrets.CONTAINER_APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --image ${{ secrets.ACR_NAME }}.azurecr.io/user-service:dev \
          --set-env-vars GITHUB_RUN_ID=${{ github.run_id }} \
          --revision-suffix rev-${{ github.run_number }} \